apiVersion: v1
kind: Service
metadata:
  name: hello-world-#{PRNUM}#
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "hello-world-#{PRNUM}#"
    port: 8080
  selector:
    app: hello-world-#{PRNUM}#

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-#{PRNUM}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-#{PRNUM}#
  template:
    metadata:
      labels:
        app: hello-world-#{PRNUM}#
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        name: hello-world-#{PRNUM}#
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          limits:
            cpu: 128m
            memory: 64Mi